name: 'Fetch CVE Data'
description: 'Fetches and pushes CVE data'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Fetch CVE data
      shell: bash
      run: |
        cd importer
        yarn run cve
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Push CVE data
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./public/cve/
        publish_branch: cve
        force_orphan: true
