name: 'Generate Treemap'
description: 'Generates and pushes treemap data'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate treemap data
      shell: bash
      run: |
        cd importer
        yarn run treemap
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Push treemap data
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./public/treemap/
        publish_branch: treemap
        force_orphan: true
